In [8]:
import tensorflow as tf

# Hypothesis using matrix

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [9]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes gloabl variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data}
    )
    if step % 500 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 142192.78 
Prediction:
 [-178.7406  -220.8423  -214.7302  -230.75406 -172.54045]
500 Cost: 18.361979 
Prediction:
 [155.06247 181.79912 181.2568  200.49916 134.90327]
1000 Cost: 14.936818 
Prediction:
 [154.40341 182.25587 181.06111 200.309   135.54369]
1500 Cost: 12.303265 
Prediction:
 [153.8304  182.65355 180.89172 200.13846 136.1061 ]
2000 Cost: 10.273982 
Prediction:
 [153.33253 182.99965 180.74527 199.98509 136.60033]


In [1]:
import tensorflow as tf

In [3]:
# 위의 코드는 너무 복잡함! 행렬로 풀자.

x_data = [    
    [73., 80., 75.],
    [93., 88., 93. ],
    [89., 91., 90.],
    [96., 98., 100.],
    [73., 66., 70.],
]
y_data = [
    [152.],
    [185.],
    [180.],
    [196.],
    [142.],
]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [6]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes gloabl variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_data, Y: y_data}
    )
    if step % 500 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 1146.4515 
Prediction:
 [[183.42755]
 [219.35095]
 [216.44507]
 [235.85367]
 [167.45625]]
500 Cost: 1.7787548 
Prediction:
 [[153.15703]
 [183.45363]
 [180.82286]
 [197.08261]
 [140.17938]]
1000 Cost: 1.4058793 
Prediction:
 [[152.93314]
 [183.60788]
 [180.75522]
 [197.02603]
 [140.3883 ]]
1500 Cost: 1.1209795 
Prediction:
 [[152.738  ]
 [183.74242]
 [180.69641]
 [196.9759 ]
 [140.57124]]
2000 Cost: 0.9031886 
Prediction:
 [[152.56801]
 [183.85973]
 [180.64528]
 [196.93144]
 [140.73149]]
